### ISSUE TITLE
Can not get the deepstream-app! How to deal with the problem?

### ISSUE THREAD

**Issue by jianyangshi** [marcoslucianops/DeepStream-Yolo-Seg#11]
@ubuntu:~/DeepStream-Yolo-Seg$ sudo CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo_seg
make: Entering directory '/home/sfhs/DeepStream-Yolo-Seg/nvdsinfer_custom_impl_Yolo_seg'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/sfhs/DeepStream-Yolo-Seg/nvdsinfer_custom_impl_Yolo_seg'

**Comment by jianyangshi** [comment]
Can you help me!

**Comment by marcoslucianops** [comment]
What's the error? That you send is only the compilation part.

**Comment by jianyangshi** [comment]
> What's the error? That you send is only the compilation part.
When i run CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo_seg,I can't get a new deepstream-app.The deepstream-app is also the detection deepstream-app! It appears the followings:
https://github.com/ubuntu:~/DeepStream-Yolo-Seg$ sudo CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo_seg
make: Entering directory '/home/sfhs/DeepStream-Yolo-Seg/nvdsinfer_custom_impl_Yolo_seg'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/sfhs/DeepStream-Yolo-Seg/nvdsinfer_custom_impl_Yolo_seg'
The error is  that, if i use  the run : deepstream-app -c deepstream_app_config.txt,i can not get the trt engine and get the seg result!

**Comment by jianyangshi** [comment]
sfhs@ubuntu:~$ cd  DeepStream-Yolo-Seg
sfhs@ubuntu:~/DeepStream-Yolo-Seg$ sudo CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo_seg
make: Entering directory '/home/sfhs/DeepStream-Yolo-Seg/nvdsinfer_custom_impl_Yolo_seg'
g++ -c  -o utils.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include utils.cpp
g++ -c  -o nvdsparseseg_Yolo.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream/sources/includes -I/usr/local/cuda-10.2/include nvdsparseseg_Yolo.cpp
g++ -o libnvdsinfer_custom_impl_Yolo_seg.so  utils.o nvdsparseseg_Yolo.o -shared -Wl,--start-group -L/usr/local/cuda-10.2/lib64 -lcudart -lcublas -lstdc++fs -Wl,--end-group
make: Leaving directory '/home/sfhs/DeepStream-Yolo-Seg/nvdsinfer_custom_impl_Yolo_seg'
sfhs@ubuntu:~/DeepStream-Yolo-Seg$ deepstream-app -c deepstream_app_config.txt
bash: deepstream-app: command not found
sfhs@ubuntu:~/DeepStream-Yolo-Seg$ sudo deepstream-app -c deepstream_app_config.txt
sudo: deepstream-app: command not found
sfhs@ubuntu:~/DeepStream-Yolo-Seg$ 
I del the old folder, i download the DeepStream-Yolo-Seg again,i compile with the command:sudo CUDA_VER=10.2 make -C nvdsinfer_custom_impl_Yolo_seg and i run the command:sudo deepstream-app -c deepstream_app_config.txt,it does nor work!
And can you give me some help?

**Comment by jianyangshi** [comment]
My hero! Please help me deal with the problem!

**Comment by jianyangshi** [comment]
sfhs@ubuntu:~/DeepStream-Yolo-Seg$ sudo deepstream-app -c deepstream_app_config.txt
[sudo] password for sfhs: 

Using winsys: x11 
ERROR: Deserialize engine failed because file path: /home/sfhs/DeepStream-Yolo-Seg/yolov8s-seg.onnx_b1_gpu0_fp32.engine open error
0:00:04.959025154 20780   0x7f4c0022d0 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1889> [UID = 1]: deserialize engine from file :/home/sfhs/DeepStream-Yolo-Seg/yolov8s-seg.onnx_b1_gpu0_fp32.engine failed
0:00:04.985145086 20780   0x7f4c0022d0 WARN                 nvinfer gstnvinfer.cpp:635:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1996> [UID = 1]: deserialize backend context from engine from file :/home/sfhs/DeepStream-Yolo-Seg/yolov8s-seg.onnx_b1_gpu0_fp32.engine failed, try rebuild
0:00:04.985276863 20780   0x7f4c0022d0 INFO                 nvinfer gstnvinfer.cpp:638:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1914> [UID = 1]: Trying to create engine from model files
WARNING: [TRT]: onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
WARNING: [TRT]: Tensor DataType is determined at build time for tensors not marked as input or output.
WARNING: [TRT]: onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
ERROR: [TRT]: ModelImporter.cpp:773: While parsing node number 449 [RoiAlign -> "/1/RoiAlign_output_0"]:
ERROR: [TRT]: ModelImporter.cpp:774: --- Begin node ---
ERROR: [TRT]: ModelImporter.cpp:775: input: "/0/model.22/proto/cv3/act/Mul_output_0"
input: "/1/Reshape_1_output_0"
input: "/1/Gather_1_output_0"
output: "/1/RoiAlign_output_0"
name: "/1/RoiAlign"
op_type: "RoiAlign"
attribute {
  name: "coordinate_transformation_mode"
  s: "half_pixel"
  type: STRING
}
attribute {
  name: "mode"
  s: "avg"
  type: STRING
}
attribute {
  name: "output_height"
  i: 160
  type: INT
}
attribute {
  name: "output_width"
  i: 160
  type: INT
}
attribute {
  name: "sampling_ratio"
  i: 0
  type: INT
}
attribute {
  name: "spatial_scale"
  f: 0.25
  type: FLOAT
}

ERROR: [TRT]: ModelImporter.cpp:776: --- End node ---
ERROR: [TRT]: ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4870 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
ERROR: Failed to parse onnx file
ERROR: failed to build network since parsing model errors.
ERROR: failed to build network.
0:00:06.420640986 20780   0x7f4c0022d0 ERROR                nvinfer gstnvinfer.cpp:632:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::buildModel() <nvdsinfer_context_impl.cpp:1934> [UID = 1]: build engine file failed
0:00:06.448205947 20780   0x7f4c0022d0 ERROR                nvinfer gstnvinfer.cpp:632:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:2020> [UID = 1]: build backend context failed
0:00:06.448358364 20780   0x7f4c0022d0 ERROR                nvinfer gstnvinfer.cpp:632:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::initialize() <nvdsinfer_context_impl.cpp:1257> [UID = 1]: generate backend failed, check config file settings
0:00:06.448914462 20780   0x7f4c0022d0 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Failed to create NvDsInferContext instance
0:00:06.449016990 20780   0x7f4c0022d0 WARN                 nvinfer gstnvinfer.cpp:841:gst_nvinfer_start:<primary_gie> error: Config file path: /home/sfhs/DeepStream-Yolo-Seg/config_infer_primary_yoloV8_seg.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
** ERROR: <main:707>: Failed to set pipeline to PAUSED
Quitting
ERROR from primary_gie: Failed to create NvDsInferContext instance
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvinfer/gstnvinfer.cpp(841): gst_nvinfer_start (): /GstPipeline:pipeline/GstBin:primary_gie_bin/GstNvInfer:primary_gie:
Config file path: /home/sfhs/DeepStream-Yolo-Seg/config_infer_primary_yoloV8_seg.txt, NvDsInfer Error: NVDSINFER_CONFIG_FAILED
App run failed

Now it is the problem!

**Comment by marcoslucianops** [comment]
Use the new update I did (compile the new lib and convert again the ONNX file with the new exporter) and it should work.
